daysUntilStale: 30

daysUntilClose: 7

exemptLabels:
  - bug
  - proposal
  - pending
  - to-do

staleLabel: stale

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

